production:
  secret_key_base: password

development:
  recaptcha_site_key: ENV['RECAPTCHA_SITE_KEY']
  recaptcha_secret_key: ENV['RECAPTCHA_SECRET_KEY']

google:
  service: GCS
  project: Reviews-demo
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: reviews_demo_bucket
